name: stoyco_shared
description: A set of shared components for Stoyco Flutter projects.
version: 0.0.25

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  country_flags: ^2.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  intl_phone_field: ^3.2.0
  reactive_forms: ^16.1.1
  vph_web_date_picker: ^0.0.5
  intl: ^0.18.1
  vph_common_widgets: ^0.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_messaging: ^14.7.15
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/home/
