name: stoyco_shared
description: A set of shared components for Stoyco Flutter projects.
version: 21.5.11

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  country_flags: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  intl_phone_field: ^3.2.0
  reactive_forms: ^18.1.1
  vph_web_date_picker: ^0.0.5
  intl: ^0.20.2
  vph_common_widgets: ^0.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  firebase_messaging: ^15.0.4
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  firebase_core_platform_interface: ^6.0.0
  glassmorphism: ^3.0.0
  gradient_borders: ^1.0.1
  dio: ^5.7.0
  either_dart: ^1.0.0
  tutorial_coach_mark: ^1.2.11
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  map_launcher: ^3.5.0
  url_launcher: ^6.3.1
  collection: ^1.18.0
  path_provider: ^2.1.1
  share_plus: ^12.0.1
  video_player: ^2.7.2
  carousel_slider: ^5.0.0
  get_thumbnail_video: ^0.7.3
  visibility_detector: ^0.4.0+2
  firebase_remote_config: ^5.4.2
  outline_gradient_button: ^2.0.1+1
  flutter_widget_from_html: ^0.17.0
  moengage_flutter: ^10.1.0
  moengage_geofence: ^6.1.0
  stoyco_interaction_content:
    git:
      url: https://github.com/StoyCompany/StoycoInteractionContent_Package.git
      ref: main
  stoyco_subscription:
    # path: ../stoyco_subscription
    git:
      url: https://github.com/StoyCompany/stoyco_subscription.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.0
  mockito: ^5.4.4

flutter:
  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/home/
    - lib/assets/gifs/
